### ISSUE TITLE
Commit style

### ISSUE THREAD

**Issue by heron2014** [DRDD2016/sparkn2#22]
Start commit with the following:

**feat**: a new feature
**fix**: a bug fix
**docs**: changes to documentation
**style**: formatting, missing semi colons, etc; no code change
**refactor**: refactoring production code
**test**: adding tests, refactoring test; no production code change
**chore**: updating build tasks, package manager configs, etc; no production code change

Reference: http://udacity.github.io/git-styleguide/

**Comment by minaorangina** [comment]
This issue was moved to DRDD2016/native#21
