### ISSUE TITLE
Variable (styles) not used

### ISSUE THREAD

**Issue by heron2014** [DRDD2016/sparkn2#23]
In components/common:

- Card - styles not used [see here](https://github.com/DRDD2016/sparkn2/blob/master/src/js/components/common/Card.js#L6)
- CardSection - styles not used [see here](https://github.com/DRDD2016/sparkn2/blob/master/src/js/components/common/CardSection.js#L13)

**Comment by minaorangina** [comment]
This issue was moved to DRDD2016/native#22
