### ISSUE TITLE
Accessing address book

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/sparkn2#39]
[Running app on device](https://facebook.github.io/react-native/docs/running-on-device.html)

**Comment by heron2014** [comment]
Our pick is: 
- https://github.com/rt2zz/react-native-contacts

**Comment by minaorangina** [comment]
### Setting up React-Native-Contacts
1. open xcode
2. expand project folder (`sparkn2`)
3. Right-click **Libraries**, select **Add files to [sparkn2]**
4. Navigate to your project's folder --> **node_modules** --> **react-native-contacts** --> **ios** --> **RCTContacts.xcodeproj**
5. Back in xcode, in the the left-hand navigator, select project folder
6. In main screen to right, select **Build Phases**
7. Select **Link Binary With Libraries**
8. Select + icon
9. select **libRCTContacts.a**

**Comment by heron2014** [comment]
Resolved by #45
