### ISSUE TITLE
Add DatePicker Android 

### ISSUE THREAD

**Issue by heron2014** [DRDD2016/sparkn2#42]
Depending on the platfiorm render specific DatePicker:

- [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html)

**Comment by rickardinho** [comment]
This might help... https://github.com/corymsmith/react-native-modal-datetime-picker/blob/master/README.md

**Comment by heron2014** [comment]
Thanks @rickardinho.

**Comment by minaorangina** [comment]
This issue was moved to DRDD2016/native#32
