### ISSUE TITLE
Analytics solution

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/sparkn2#59]
I am currently favouring Twitter's Fabric (including Crashlytics and Answers) for analytics.  There is a library for react native for this... I'll post a link.

**Comment by rickardinho** [comment]
https://github.com/corymsmith/react-native-fabric/blob/master/README.md#crashlytics-usage

**Comment by rickardinho** [comment]
I managed to get a test app up and running for this in just 20minutes, so happy for you to leave this and I can add analytics at the end.

**Comment by minaorangina** [comment]
This issue was moved to DRDD2016/native#45
