### ISSUE TITLE
Save token to the Async Storage, redirection, checking for token existence

### ISSUE THREAD

**Issue by heron2014** [DRDD2016/sparkn2#66]
- [x] from intro page redirect user either to login or sign up page
- [ ] save token to the Async Storage #67
- [x] redirect user after signing up to the upload photo page [reference](https://github.com/exponent/ex-navigation#perform-navigation-actions-from-outside-of-a-component)
- [x] create basic upload photo page 
- [x] redirect from upload photo page to Feed
- [ ] check for existence of token on App Container
- [ ] authenticated users (token exist) redirect user straight away to Feed page

**Comment by minaorangina** [comment]
This issue was moved to DRDD2016/native#48
