### ISSUE TITLE
Issue with redirection (Navigation, babel)

### ISSUE THREAD

**Issue by heron2014** [DRDD2016/sparkn2#68]
We are trying to do redirection from outside of the component as the documentation says: 
- https://github.com/exponent/ex-navigation#perform-navigation-actions-from-outside-of-a-component

We have following bug when we import our Router:

![screen shot 2017-01-06 at 17 56 37](https://cloud.githubusercontent.com/assets/8476884/21727602/fc8240cc-d439-11e6-94a0-2447ecae5b41.png)

References:
- .../facebook/jest/issues/1812
- http://stackoverflow.com/questions/34444716/babelrc-ignore-field-seems-to-be-ignored

**Comment by minaorangina** [comment]
see #67
