### ISSUE TITLE
Date and Time pickers for inputs

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/sparkn2#7]
I have currently left this as Text input for simplicity for now, but will have a look at DatePicker solutions.  React native has seperate pickers for iOS and Android, so we might need to have separate components for each.  Leave this for Dave to look at.

**Comment by heron2014** [comment]
Hi @rickardinho

Have you done any research on this yet? If yes, please put the link to the module. Thanks

**Comment by heron2014** [comment]
Hi again @rickardinho 

Actually there is a way to render specific DatePicker component depending on which platform is being used. React native can detect which operating system is being used. 

Since it needs to be hooked up with redux we think we will implement that.

**Comment by rickardinho** [comment]
That was the conclusion I was coming to. There doesn't seem to be a cross-platform solution.  Happy for you to go ahead with what you think works for now.

**Comment by minaorangina** [comment]
This issue was moved to DRDD2016/native#10
